In [14]:
import pandas as pd
import numpy as np

# 5.1 pandas的数据结构介绍

## Series

In [6]:
obj = pd.Series([4, 7, -5, 3])
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [7]:
obj.values  # 查看值属性

array([ 4,  7, -5,  3], dtype=int64)

In [8]:
obj.index  # 查看位置索引属性

RangeIndex(start=0, stop=4, step=1)

In [9]:
obj2 = pd.Series([4, 7, -5, 3], index=['d', 'b', 'a', 'c'])  # 设置索引（index）
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [11]:
obj2['a']              # 通过索引选择单一值
obj2[['c', 'a', 'd']]  # 通过索引选择多个值
obj2['d'] = 6          # 赋值

In [12]:
obj2[obj2 > 0]  # 布尔过滤

d    6
b    7
c    3
dtype: int64

In [13]:
obj2 * 2  # 运算

d    12
b    14
a   -10
c     6
dtype: int64

In [15]:
np.exp(obj2)  # 应用数学函数

d     403.428793
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

In [16]:
'b' in obj2  # 查看是否包含指定索引，Service 也是一个定长的有序字典

True

In [18]:
sdata = {'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}
obj3 = pd.Series(sdata)  # 通过字典创建 Service
obj3

Ohio      35000
Oregon    16000
Texas     71000
Utah       5000
dtype: int64

In [19]:
states = ['California', 'Ohio', 'Oregon', 'Texas']
obj4 = pd.Series(sdata, index=states)  # 传入排序好的字典键，注意：obj4 中 'California' 为 NaN、 'Utah' 被丢弃
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [20]:
pd.isnull(obj4)  # 检测是否为 NaN

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [21]:
pd.notnull(obj4)  # 检测是否不是 NaN

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [22]:
obj4.isnull()  # Series 的检测是否为 NaN

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [23]:
obj3 + obj4  # Service 可以自动对齐然后运算

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

In [24]:
# Service 的 name 属性
obj4.name = 'population'
obj4.index.name = 'state'
obj4

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

In [25]:
obj.index = ['Bob', 'Steve', 'Jeff', 'Ryan']  # index 可以直接通过赋值设置
obj

Bob      4
Steve    7
Jeff    -5
Ryan     3
dtype: int64

In [37]:
obj.index = ['abc', 'Steve', 'Jeff', 'Ryan']  # 修改 index
obj.index[0]

'abc'

## DataFrame

In [39]:
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'], 
        'year': [2000, 2001, 2002, 2001, 2002, 2003], 
        'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}
frame = pd.DataFrame(data)  # 通过字典创建 DataFrame
frame

pop   state  year
0  1.5    Ohio  2000
1  1.7    Ohio  2001
2  3.6    Ohio  2002
3  2.4  Nevada  2001
4  2.9  Nevada  2002
5  3.2  Nevada  2003

In [40]:
frame.head()  # 预览，默认前 5 行

pop   state  year
0  1.5    Ohio  2000
1  1.7    Ohio  2001
2  3.6    Ohio  2002
3  2.4  Nevada  2001
4  2.9  Nevada  2002

In [41]:
pd.DataFrame(data, columns=['year', 'state', 'pop'])  # 指定列（columns）顺序

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

In [42]:
frame2 = pd.DataFrame(data, 
                      columns=['year', 'state', 'pop', 'debt'], 
                      index=['one', 'two', 'three', 'four','five', 'six'])  # 传入的 columns 在数据中找不到则为 NaN
frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN

In [45]:
# 下面两种方式都可以选择列
frame2['state']  # 字典标记（适用于任何列名，建议使用）
frame2.state     # 查看属性（列名是一个合理的 Python 变量名时才适用）

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
six      Nevada
Name: state, dtype: object

In [46]:
frame2[['year', 'state']]  # 选择多列

year   state
one    2000    Ohio
two    2001    Ohio
three  2002    Ohio
four   2001  Nevada
five   2002  Nevada
six    2003  Nevada

In [47]:
frame2['debt'] = 16.5  # 赋标量值
frame2

year   state  pop  debt
one    2000    Ohio  1.5  16.5
two    2001    Ohio  1.7  16.5
three  2002    Ohio  3.6  16.5
four   2001  Nevada  2.4  16.5
five   2002  Nevada  2.9  16.5
six    2003  Nevada  3.2  16.5

In [48]:
frame2['debt'] = range(6)  # 赋一组值
frame2

year   state  pop  debt
one    2000    Ohio  1.5     0
two    2001    Ohio  1.7     1
three  2002    Ohio  3.6     2
four   2001  Nevada  2.4     3
five   2002  Nevada  2.9     4
six    2003  Nevada  3.2     5

In [49]:
val = pd.Series([-1.2, -1.5, -1.7], index=['two', 'four', 'five'])  # 用 Service 赋值则会精确匹配 index，空值为 NaN
frame2['debt'] = val
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   NaN

In [50]:
frame2['eastern'] = frame2.state == 'Ohio'  # 为不存在的列赋值会创建新列，注意：不能用 frame2.eastern 创建新列
frame2

year   state  pop  debt  eastern
one    2000    Ohio  1.5   NaN     True
two    2001    Ohio  1.7  -1.2     True
three  2002    Ohio  3.6   NaN     True
four   2001  Nevada  2.4  -1.5    False
five   2002  Nevada  2.9  -1.7    False
six    2003  Nevada  3.2   NaN    False

In [51]:
del frame2['eastern']  # 使用 del 删除列
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   NaN

In [55]:
frame3 = frame2.copy()  # copy() 函数可以值传递

In [56]:
pop = {'Nevada': {2001: 2.4, 2002: 2.9},
       'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}
frame3 = pd.DataFrame(pop)  # 通过嵌套字典创建 DataFrame
frame3

Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7
2002     2.9   3.6

In [57]:
frame3.T  # 转置

2000  2001  2002
Nevada   NaN   2.4   2.9
Ohio     1.5   1.7   3.6

In [59]:
pdata = {'Ohio': frame3['Ohio'][:-1],
         'Nevada': frame3['Nevada'][:2]}
pd.DataFrame(pdata)  # 通过 Series 组成的字典创建 DataFrame

Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7

In [60]:
# DataFrame 设置 name 属性
frame3.index.name = 'year'
frame3.columns.name = 'state' 
frame3

state  Nevada  Ohio
year               
2000      NaN   1.5
2001      2.4   1.7
2002      2.9   3.6

In [61]:
frame3.index

Int64Index([2000, 2001, 2002], dtype='int64', name='year')

In [62]:
frame3.columns

Index(['Nevada', 'Ohio'], dtype='object', name='state')

In [63]:
frame3.values  # DataFrame 以二维数组的方式返回数据

array([[nan, 1.5],
       [2.4, 1.7],
       [2.9, 3.6]])

In [64]:
frame2.values  # DataFrame 会兼容所有列的数据类型

array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, -1.2],
       [2002, 'Ohio', 3.6, nan],
       [2001, 'Nevada', 2.4, -1.5],
       [2002, 'Nevada', 2.9, -1.7],
       [2003, 'Nevada', 3.2, nan]], dtype=object)

## 索引对象

In [2]:
# 5.2 基本功能

In [ ]:
# 重新索引
