In [1]:
import pandas as pd
import numpy as np

# 5.1 pandas的数据结构介绍

## Series

In [2]:
obj = pd.Series([4, 7, -5, 3])
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [3]:
obj.values  # 查看值属性

array([ 4,  7, -5,  3], dtype=int64)

In [4]:
obj.index  # 查看位置索引属性

RangeIndex(start=0, stop=4, step=1)

In [5]:
obj2 = pd.Series([4, 7, -5, 3], index=['d', 'b', 'a', 'c'])  # 设置索引（index）
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [6]:
obj2['a']              # 通过索引选择单一值
obj2[['c', 'a', 'd']]  # 通过索引选择多个值
obj2['d'] = 6          # 赋值

In [7]:
obj2[obj2 > 0]  # 布尔过滤

d    6
b    7
c    3
dtype: int64

In [8]:
obj2 * 2  # 运算

d    12
b    14
a   -10
c     6
dtype: int64

In [9]:
np.exp(obj2)  # 应用数学函数

d     403.428793
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

In [10]:
'b' in obj2  # 查看是否包含指定索引，Service 也是一个定长的有序字典

True

In [11]:
sdata = {'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}
obj3 = pd.Series(sdata)  # 通过字典创建 Service
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [12]:
states = ['California', 'Ohio', 'Oregon', 'Texas']
obj4 = pd.Series(sdata, index=states)  # 传入排序好的字典键，注意：obj4 中 'California' 为 NaN、 'Utah' 被丢弃
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [13]:
pd.isnull(obj4)  # 检测是否为 NaN

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [14]:
pd.notnull(obj4)  # 检测是否不是 NaN

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [15]:
obj4.isnull()  # Series 的检测是否为 NaN

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [16]:
obj3 + obj4  # Service 可以自动对齐然后运算

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

In [17]:
# Service 的 name 属性
obj4.name = 'population'
obj4.index.name = 'state'
obj4

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

In [18]:
obj.index = ['Bob', 'Steve', 'Jeff', 'Ryan']  # index 可以直接通过赋值设置
obj

Bob      4
Steve    7
Jeff    -5
Ryan     3
dtype: int64

In [19]:
obj.index = ['abc', 'Steve', 'Jeff', 'Ryan']  # 修改 index
obj.index[0]

'abc'

## DataFrame

In [20]:
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'], 
        'year': [2000, 2001, 2002, 2001, 2002, 2003], 
        'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}
frame = pd.DataFrame(data)  # 通过字典创建 DataFrame
frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [21]:
frame.head()  # 预览，默认前 5 行

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [22]:
pd.DataFrame(data, columns=['year', 'state', 'pop'])  # 指定列（columns）顺序

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

In [23]:
frame2 = pd.DataFrame(data, 
                      columns=['year', 'state', 'pop', 'debt'], 
                      index=['one', 'two', 'three', 'four','five', 'six'])  # 传入的 columns 在数据中找不到则为 NaN
frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN

In [24]:
# 下面两种方式都可以选择列
frame2['state']  # 字典标记（适用于任何列名，建议使用）
frame2.state     # 查看属性（列名是一个合理的 Python 变量名时才适用）

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
six      Nevada
Name: state, dtype: object

In [25]:
frame2[['year', 'state']]  # 选择多列

year   state
one    2000    Ohio
two    2001    Ohio
three  2002    Ohio
four   2001  Nevada
five   2002  Nevada
six    2003  Nevada

In [26]:
frame2['debt'] = 16.5  # 赋标量值
frame2

year   state  pop  debt
one    2000    Ohio  1.5  16.5
two    2001    Ohio  1.7  16.5
three  2002    Ohio  3.6  16.5
four   2001  Nevada  2.4  16.5
five   2002  Nevada  2.9  16.5
six    2003  Nevada  3.2  16.5

In [27]:
frame2['debt'] = range(6)  # 赋一组值
frame2

year   state  pop  debt
one    2000    Ohio  1.5     0
two    2001    Ohio  1.7     1
three  2002    Ohio  3.6     2
four   2001  Nevada  2.4     3
five   2002  Nevada  2.9     4
six    2003  Nevada  3.2     5

In [28]:
val = pd.Series([-1.2, -1.5, -1.7], index=['two', 'four', 'five'])  # 用 Service 赋值则会精确匹配 index，空值为 NaN
frame2['debt'] = val
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   NaN

In [29]:
frame2['eastern'] = frame2.state == 'Ohio'  # 为不存在的列赋值会创建新列，注意：不能用 frame2.eastern 创建新列
frame2

year   state  pop  debt  eastern
one    2000    Ohio  1.5   NaN     True
two    2001    Ohio  1.7  -1.2     True
three  2002    Ohio  3.6   NaN     True
four   2001  Nevada  2.4  -1.5    False
five   2002  Nevada  2.9  -1.7    False
six    2003  Nevada  3.2   NaN    False

In [30]:
del frame2['eastern']  # 使用 del 删除列
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   NaN

In [31]:
frame3 = frame2.copy()  # copy() 函数可以值传递
frame3['year'] = 0
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   NaN

In [32]:
pop = {'Nevada': {2001: 2.4, 2002: 2.9},
       'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}
frame3 = pd.DataFrame(pop)  # 通过嵌套字典创建 DataFrame
frame3

Nevada  Ohio
2000     NaN   1.5
2001     2.4   1.7
2002     2.9   3.6

In [33]:
frame3.T  # 转置

2000  2001  2002
Nevada   NaN   2.4   2.9
Ohio     1.5   1.7   3.6

In [34]:
pdata = {'Ohio': frame3['Ohio'][:-1],
         'Nevada': frame3['Nevada'][:2]}
pd.DataFrame(pdata)  # 通过 Series 组成的字典创建 DataFrame

Ohio  Nevada
2000   1.5     NaN
2001   1.7     2.4

In [35]:
# DataFrame 设置 name 属性
frame3.index.name = 'year'
frame3.columns.name = 'state' 
frame3

state  Nevada  Ohio
year               
2000      NaN   1.5
2001      2.4   1.7
2002      2.9   3.6

In [36]:
frame3.index

Int64Index([2000, 2001, 2002], dtype='int64', name='year')

In [37]:
frame3.columns

Index(['Nevada', 'Ohio'], dtype='object', name='state')

In [38]:
frame3.values  # DataFrame 以二维数组的方式返回数据

array([[nan, 1.5],
       [2.4, 1.7],
       [2.9, 3.6]])

In [39]:
frame2.values  # DataFrame 会兼容所有列的数据类型

array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, -1.2],
       [2002, 'Ohio', 3.6, nan],
       [2001, 'Nevada', 2.4, -1.5],
       [2002, 'Nevada', 2.9, -1.7],
       [2003, 'Nevada', 3.2, nan]], dtype=object)

## 索引对象

In [40]:
obj = pd.Series(range(3), index=['a', 'b', 'c'])
index = obj.index
print(index)
print(index[1:])

Index(['a', 'b', 'c'], dtype='object')
Index(['b', 'c'], dtype='object')


In [41]:
frame3

state  Nevada  Ohio
year               
2000      NaN   1.5
2001      2.4   1.7
2002      2.9   3.6

In [42]:
'Ohio' in frame3.columns  # columns 是否包含指定值

True

In [43]:
2003 in frame3.index   # index 是否包含指定值

False

In [44]:
frame3.index = [200, 200, 202]  # DataFrame 的 index 属性可以整体更改，可以有重复项
frame3

state  Nevada  Ohio
200       NaN   1.5
200       2.4   1.7
202       2.9   3.6

In [45]:
frame3.loc[200]  # 选择重复的标签，会显示所有结果

state  Nevada  Ohio
200       NaN   1.5
200       2.4   1.7

# 5.2 基本功能

## 重新索引

In [46]:
obj= pd.Series([4.5, 7.2, -5.3, 3.6], index=['d', 'b', 'a', 'c'])
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [47]:
obj2 = obj.reindex(['a', 'b', 'c', 'd', 'e'])  # reindex() 修改 Serie 索引
obj2

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [48]:
obj3 = pd.Series(['blue', 'purple', 'yellow'], index=[0, 2, 4])
obj3.reindex(range(6), method='ffill')  # ffill 向前值填充，也就是取前一个值

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [49]:
frame = pd.DataFrame(np.arange(9).reshape((3, 3)),
                     index=['a', 'c', 'd'],
                     columns=['Ohio', 'Texas', 'California'])
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [50]:
frame2 = frame.reindex(index=['a', 'b', 'c', 'd'], 
                       columns=['Texas', 'Utah', 'California'])  # reindex() 修改 DataFrame 索引
frame2

Texas  Utah  California
a    1.0   NaN         2.0
b    NaN   NaN         NaN
c    4.0   NaN         5.0
d    7.0   NaN         8.0

## 丢弃指定轴上的项

In [51]:
obj = pd.Series(np.arange(5.),
               index=['a', 'b', 'c', 'd', 'e'])
obj

a    0.0
b    1.0
c    2.0
d    3.0
e    4.0
dtype: float64

In [52]:
new_obj = obj.drop(['d', 'c']) # drop() 丢弃 Serie 指定值
new_obj

a    0.0
b    1.0
e    4.0
dtype: float64

In [53]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)), 
                    index=['Ohio', 'Colorado', 'Utah', 'New York'], 
                    columns=['one', 'two', 'three', 'four'])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [54]:
data.drop(['Colorado', 'Ohio'])  # drop() 丢弃 DataFrame 指定值（丢弃行）

one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

In [55]:
data.drop('one', axis='columns')  # drop() 丢弃 DataFrame 指定值（丢弃列）

two  three  four
Ohio        1      2     3
Colorado    5      6     7
Utah        9     10    11
New York   13     14    15

## 索引、选取和过滤

In [56]:
obj = pd.Series(np.arange(4.), index=['a', 'b', 'c', 'd'])
obj

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [57]:
obj['b']

1.0

In [58]:
obj[1]

1.0

In [59]:
obj[1:4]

b    1.0
c    2.0
d    3.0
dtype: float64

In [60]:
obj[['b', 'c', 'd']]

b    1.0
c    2.0
d    3.0
dtype: float64

In [61]:
obj['b':'d']

b    1.0
c    2.0
d    3.0
dtype: float64

In [62]:
obj[obj < 2]

a    0.0
b    1.0
dtype: float64

In [63]:
obj['b':'d'] = 5
obj

a    0.0
b    5.0
c    5.0
d    5.0
dtype: float64

In [64]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),
                    index=['Ohio', 'Colorado', 'Utah', 'New York'],
                    columns=['one', 'two', 'three', 'four'])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [65]:
data['two']  # 选择列

Ohio         1
Colorado     5
Utah         9
New York    13
Name: two, dtype: int32

In [66]:
data[['three', 'one']]  # 选择多列

three  one
Ohio          2    0
Colorado      6    4
Utah         10    8
New York     14   12

In [67]:
data[:2]  # 选择行

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7

In [68]:
data[data['three'] > 5]  # 布尔条件选择

one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [69]:
data[data < 5] = 0
data

one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

## 用 loc 和 iloc 进行选取

In [70]:
data.loc['Colorado', ['two', 'three']]  # loc（location） 轴标签

two      5
three    6
Name: Colorado, dtype: int32

In [71]:
data.iloc[1, [1, 2]]  # iloc（int location） 整数索引

two      5
three    6
Name: Colorado, dtype: int32

In [72]:
data.loc[:'Utah', 'two']  # loc 切片(包含末尾)

Ohio        0
Colorado    5
Utah        9
Name: two, dtype: int32

In [73]:
data.iloc[:3, 1]  # iloc 切片（不包含末尾）

Ohio        0
Colorado    5
Utah        9
Name: two, dtype: int32

## 整数索引

In [74]:
ser = pd.Series(np.arange(3.))  # 采用整数索引会产生歧义
# ser[-1]
ser

0    0.0
1    1.0
2    2.0
dtype: float64

In [75]:
ser2 = pd.Series(np.arange(3.), index=['a', 'b', 'c'])  # 设置 index 可消除歧义
ser2[-1]

2.0

In [76]:
ser.iloc[-1]  # 使用 iloc 或 loc ，明确整数索引或标签索引可以消除歧义

2.0

In [77]:
ser.loc[2]

2.0

## 算术运算和数据对齐

In [78]:
s1 = pd.Series([7.3, -2.5, 3.4, 1.5], index=['a', 'c', 'd', 'e'])
s2 = pd.Series([-2.1, 3.6, -1.5, 4, 3.1], index=['a', 'c', 'e', 'f', 'g'])

In [79]:
s1 + s2 

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [80]:
df1 = pd.DataFrame(np.arange(9.).reshape((3, 3)), 
                   columns=list('bcd'), 
                   index=['Ohio', 'Texas', 'Colorado']) 
df2 = pd.DataFrame(np.arange(12.).reshape((4, 3)), 
                   columns=list('bde'), 
                   index=['Utah', 'Ohio', 'Texas', 'Oregon'])

In [81]:
df1 + df2

b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

In [82]:
df1 = pd.DataFrame({'A': [1, 2]})
df2 = pd.DataFrame({'B': [3, 4]})

In [83]:
df1 + df2  # 由于两个 DataFrame 完全没有共同的列或行，所以结果全部为 NaN

A   B
0 NaN NaN
1 NaN NaN

## 在算术方法中填充值

In [84]:
df1 = pd.DataFrame(np.arange(12.).reshape((3, 4)),
                   columns=list('abcd'))
df2 = pd.DataFrame(np.arange(20.).reshape((4, 5)),
                   columns=list('abcde'))
df2.loc[1, 'b'] = np.NaN

In [85]:
df1 + df2

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0   NaN  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [86]:
df1.add(df2, fill_value=0)  # add() 相加，fill_value 属性空值用 0 代替

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0   5.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [87]:
df1.sub(df2, fill_value=0)  # sub() 相减

a     b     c     d     e
0   0.0   0.0   0.0   0.0  -4.0
1  -1.0   5.0  -1.0  -1.0  -9.0
2  -2.0  -2.0  -2.0  -2.0 -14.0
3 -15.0 -16.0 -17.0 -18.0 -19.0

In [88]:
df1.div(df2, fill_value=0)  # div() 相除（/）

a         b         c         d    e
0  NaN  1.000000  1.000000  1.000000  0.0
1  0.8       inf  0.857143  0.875000  0.0
2  0.8  0.818182  0.833333  0.846154  0.0
3  0.0  0.000000  0.000000  0.000000  0.0

In [89]:
df1.floordiv(df2, fill_value=0)  # floordiv() 底除（整除 //）

a    b    c    d    e
0  NaN  1.0  1.0  1.0 -0.0
1  0.0  NaN  0.0  0.0 -0.0
2  0.0  0.0  0.0  0.0 -0.0
3 -0.0 -0.0 -0.0 -0.0 -0.0

In [90]:
df1.mul(df2, fill_value=0)  # mul() 相乘（*）

a     b      c      d    e
0   0.0   1.0    4.0    9.0  0.0
1  20.0   0.0   42.0   56.0  0.0
2  80.0  99.0  120.0  143.0  0.0
3   0.0   0.0    0.0    0.0  0.0

In [91]:
df1.pow(df2, fill_value=0)  # pow() 指数（**）

a             b             c             d    e
0  1.000000e+00  1.000000e+00  4.000000e+00  2.700000e+01  0.0
1  1.024000e+03  1.000000e+00  2.799360e+05  5.764801e+06  0.0
2  1.073742e+09  3.138106e+10  1.000000e+12  3.452271e+13  0.0
3  0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00  0.0

In [92]:
df1.reindex(columns=df2.columns, fill_value=0)  # 修改索引时也可指定填充值

a    b     c     d  e
0  0.0  1.0   2.0   3.0  0
1  4.0  5.0   6.0   7.0  0
2  8.0  9.0  10.0  11.0  0

## DataFrame和Series之间的运算

In [93]:
arr = np.arange(12.).reshape((3, 4))
arr

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [94]:
arr - arr[0]  # 广播（行）

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

In [95]:
frame = pd.DataFrame(np.arange(12.).reshape((4, 3)),
                     columns=list('bde'),
                     index=['Utah', 'Ohio', 'Texas', 'Oregon'])
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [96]:
series = frame.iloc[0]
series

b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

In [97]:
frame - series

b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

In [98]:
series2 = pd.Series(range(3), index=['b', 'e', 'f'])
frame + series2

b   d     e   f
Utah    0.0 NaN   3.0 NaN
Ohio    3.0 NaN   6.0 NaN
Texas   6.0 NaN   9.0 NaN
Oregon  9.0 NaN  12.0 NaN

In [99]:
series3 = frame['d']
series3

Utah       1.0
Ohio       4.0
Texas      7.0
Oregon    10.0
Name: d, dtype: float64

In [100]:
frame.sub(series3, axis='index')  # 想广播列就需要用算数运算方法，并制定行或列

b    d    e
Utah   -1.0  0.0  1.0
Ohio   -1.0  0.0  1.0
Texas  -1.0  0.0  1.0
Oregon -1.0  0.0  1.0

In [101]:
frame-series3

Ohio  Oregon  Texas  Utah   b   d   e
Utah     NaN     NaN    NaN   NaN NaN NaN NaN
Ohio     NaN     NaN    NaN   NaN NaN NaN NaN
Texas    NaN     NaN    NaN   NaN NaN NaN NaN
Oregon   NaN     NaN    NaN   NaN NaN NaN NaN

## 函数应用和映射

In [102]:
frame = pd.DataFrame(np.random.randn(4, 3), columns=list('bde'), index=['Utah', 'Ohio', 'Texas', 'Oregon'])
print(frame)
print()

np.abs(frame)  # Numpy 的 ufuncs 也可用于 pandas 对象。

               b         d         e
Utah    1.745520  0.934271 -0.044046
Ohio    0.204235 -0.940745  0.271698
Texas   0.796905  0.299513 -0.543358
Oregon  1.973633 -0.935730  1.261479



b         d         e
Utah    1.745520  0.934271  0.044046
Ohio    0.204235  0.940745  0.271698
Texas   0.796905  0.299513  0.543358
Oregon  1.973633  0.935730  1.261479

In [108]:
f = lambda x: x.max() - x.min()

print(frame.apply(f))  # 将函数应用到 Dataframe 的每个列，利用 Dataframe 的 apply() 方法来实现这个功能。
print()
frame.apply(f, axis='columns')  # 将函数应用到 Dataframe 的每个行，给 apply() 方法添加 axis 属性即可。

b    1.769399
d    1.875016
e    1.804837
dtype: float64



Utah      1.789566
Ohio      1.212443
Texas     1.340263
Oregon    2.909363
dtype: float64

传递到 apply() 的函数不是必须返回标量，也可以返回多个值组成的 Series

In [109]:
def f(x):
    return pd.Series([x.min(), x.max()], index=['min', 'max'])

frame.apply(f)

b         d         e
min  0.204235 -0.940745 -0.543358
max  1.973633  0.934271  1.261479

applymap() 方法：将函数作用于 Dataframe 的每个元素

In [110]:
format = lambda x: '%.2f' % x

frame.applymap(format)

b      d      e
Utah    1.75   0.93  -0.04
Ohio    0.20  -0.94   0.27
Texas   0.80   0.30  -0.54
Oregon  1.97  -0.94   1.26

map() 方法：依次递归。applymap() 方法的名字由来和 map() 方法有关

In [111]:
frame['e'].map(format)

Utah      -0.04
Ohio       0.27
Texas     -0.54
Oregon     1.26
Name: e, dtype: object

## 排序和排名

### sort_index()：按照索引排序，默认返回新对象。

In [128]:
obj = pd.Series(range(4), index=['d', 'a', 'b', 'c'])
print(obj)
print()

obj.sort_index()

d    0
a    1
b    2
c    3
dtype: int64



a    1
b    2
c    3
d    0
dtype: int64

对于 Dataframe，可以通过 axis 属性设置按照 index 或 columns 排序

In [137]:
frame = pd.DataFrame(np.arange(8).reshape((2, 4)), index=['three', 'one'], columns=['d', 'a', 'b', 'c'])
print(frame)
print()

print(frame.sort_index())  # 按照 index 排序
print()

print(frame.sort_index(axis='columns'))  # 按照 columns 排序
print()

print(frame.sort_values(by='a'))  # 按照指定列的值排序

       d  a  b  c
three  0  1  2  3
one    4  5  6  7

       d  a  b  c
one    4  5  6  7
three  0  1  2  3

       a  b  c  d
three  1  2  3  0
one    5  6  7  4

       d  a  b  c
three  0  1  2  3
one    4  5  6  7


ascending 属性：设置升降序排序，默认升序

In [139]:
frame.sort_index(axis='columns', ascending=False)

d  c  b  a
three  0  3  2  1
one    4  7  6  5

### sort_values() 方法：按照值排序

In [140]:
# 对 Series
obj.sort_values()

d    0
a    1
b    2
c    3
dtype: int64

缺失值会放到末尾

In [142]:
obj = pd.Series([4, np.nan, 7, np.nan, -3, 2])
obj.sort_values()

4   -3.0
5    2.0
0    4.0
2    7.0
1    NaN
3    NaN
dtype: float64